----
title: static code analysis
output: markdown_document
----

```{r}
# Load necessary libraries
library(lintr)
library(dplyr)
library(progress)
```

Run lintr on a nested directory

```{r}
run_lintr_on_directory <- function(directory) {
  file_paths <- list.files(path = directory, pattern = "\\.R$", full.names = TRUE, recursive = TRUE)
  lint_summary_list <- vector("list", length(file_paths))

    # Initialize the progress bar
  pb <- progress_bar$new(total = length(file_paths), format = "[:bar] :percent :eta", clear = FALSE)

  for (i in seq_along(file_paths)) {
    file_path <- file_paths[i]
    code <- readLines(file_path)

    tryCatch({
      sum_out <- suppressWarnings(summary(lint(text = code)))
      rownames(sum_out) <- NULL
      lint_summary_list[[i]] <- sum_out
    }, error = function(e) {
      # Handle any errors that occur during linting
      cat(paste("Error linting file", file_path, ":", conditionMessage(e), "\n"))
    })
    
    pb$tick()  # Update the progress bar
  }
  return(bind_rows(lint_summary_list))
}
```

Let's piecemeal this.

```{r}
# Provide the path to the root directory containing R files
root_directory <- "../data/ajps_datasets_files/"

# Run lintr on all R files in the directory and its subdirectories
ajps_lint_results <- run_lintr_on_directory(root_directory)

mean(ajps_lint_results$style, na.rm = T)
mean(ajps_lint_results$error, na.rm = T)
mean(ajps_lint_results$warning, na.rm = T)
```
